# Project information
site_name: 夢地図
site_description: Zhan Ziyuan's blog
site_author: zhanziyuan
site_url: https://zhanziyuan.github.io/

# Repository
repo_name: zhanziyuan.github.io
repo_url: https://github.com/ZhanZiyuan/zhanziyuan.github.io/

# Copyright
copyright: Copyright &copy; 2024 - 2025 Zhan Ziyuan

# Configuration
theme:
  name: material
  palette:
    primary: deep purple
    accent: deep purple
  feature:
    tabs: true
  font:
    text: Roboto
    code: Inconsolata
  logo:
    # icon: school
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.png # https://jdenticon.com/#icon-Juliana
  language: zh

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZhanZiyuan/
  analytics:
    provider: google
    property: G-2JG9LL1KDQ

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

# Plugins
plugins:
  - search:
      lang:
        - zh
        - en

# Page tree
nav:
  - Home: index.md
  - Contents:
      - Introduction: introduction.md
      - Marxism: marxism.md
      - Frankfurt School: frankfurt_school.md
      - Biao Xiang: biao_xiang.md
      - The Self as Method: the_self_as_method.md
      - Michael Sandel: michael_sandel.md
      - AI and Society: ai_and_society.md
      - Reading: reading.md
      - Anime: anime.md
      - WeChat: wechat.md
      - References: references.md
