# Project information
site_name: 夢地図
site_description: Zhan Ziyuan's blog
site_author: zhanziyuan
site_url: https://dreammap.org/ # https://zhanziyuan.github.io/

# Repository
repo_name: zhanziyuan.github.io
repo_url: https://github.com/ZhanZiyuan/zhanziyuan.github.io/

# Copyright
copyright: Copyright &copy; 2025 Zhan Ziyuan

# Configuration
theme:
  name: material
  palette:
    primary: deep purple
    accent: deep purple
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
  font:
    text: Roboto
    code: Inconsolata
  logo:
    # icon: school
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.png # https://jdenticon.com/#icon-Juliana
  language: zh
  include_search_page: false
  search_index_only: true
  custom_dir: overrides

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZhanZiyuan/
  analytics:
    provider: google
    property: G-2JG9LL1KDQ

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

# Plugins
plugins:
  - search:
      lang:
        - zh
        - en

# Page tree
nav:
  - Home: index.md
  - Contents:
      - Introduction: introduction.md
      - Marxism: marxism.md
      - Frankfurt School: frankfurt_school.md
      - Biao Xiang: biao_xiang.md
      - The Self as Method: the_self_as_method.md
      - Hello, Stranger: hello_stranger.md
      - Capitalism as Battles over Vital Forces: capitalism_as_battles_over_vital_forces.md
      - Michael Sandel: michael_sandel.md
      - Human Predicament: human_predicament.md
      - Bullshit Jobs: bullshit_jobs.md
      - Byung-Chul Han: byung_chul_han.md
      - AI and Society: ai_and_society.md
      - The End of History and the Last Man: the_end_of_history_and_the_last_man.md
      - The Art of War: the_art_of_war.md
      - Reading: reading.md
      - Zhihu: zhihu.md
      - Rick and Morty: rick_and_morty.md
      - Anime: anime.md
      - WeChat: wechat.md
      - References: references.md
